{% set name = "de-risikogebiete" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/de-risikogebiete-{{ version }}.tar.gz
  sha256: 9246adea4acf68fc8bce7174e813857c107086fc19f5a7ad78ff6dab284416c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - python >={{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.risikogebiete
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bundesAPI/risikogebiete-api
  summary: 'Robert Koch Institut: Corona Risikogebiete API'
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
